"""Type stubs for the tuncore native Rust extension (PyO3)."""

class IdentityKeyPair:
    @staticmethod
    def generate() -> IdentityKeyPair: ...
    @property
    def public_key(self) -> bytes: ...
    def encrypt_to_store(self, passphrase: bytes) -> bytes: ...
    @staticmethod
    def decrypt_from_store(blob: bytes, passphrase: bytes) -> IdentityKeyPair: ...
    def derive_hmac_key(self, context: bytes) -> bytes: ...
    def zeroize(self) -> None: ...

class ReplayWindow:
    def __init__(self) -> None: ...
    def check_and_update(self, seq: int) -> bool: ...
    def check(self, seq: int) -> bool: ...
    def update(self, seq: int) -> None: ...
    @property
    def max_seq(self) -> int: ...

class NonceGenerator:
    def __init__(self, epoch: int) -> None: ...
    def next(self) -> bytes: ...
    @property
    def count(self) -> int: ...
    @property
    def epoch(self) -> int: ...

class NoiseInitiator:
    def __init__(self, identity: IdentityKeyPair) -> None: ...
    def write_message_1(self) -> bytes: ...
    def read_message_2(self, msg: bytes) -> bytes: ...
    def write_message_3(self) -> bytes: ...
    def into_transport(self) -> NoiseTransport: ...
    def get_handshake_hash(self) -> bytes: ...

class NoiseResponder:
    def __init__(self, identity: IdentityKeyPair) -> None: ...
    def read_message_1(self, msg: bytes) -> None: ...
    def write_message_2(self) -> bytes: ...
    def read_message_3(self, msg: bytes) -> bytes: ...
    def into_transport(self) -> NoiseTransport: ...
    def get_handshake_hash(self) -> bytes: ...

class NoiseTransport:
    def encrypt(self, plaintext: bytes) -> bytes: ...
    def decrypt(self, ciphertext: bytes) -> bytes: ...

class SessionKeyManager:
    @staticmethod
    def from_handshake_hash(
        hash: bytes, is_initiator: bool, initial_epoch: int
    ) -> SessionKeyManager: ...
    def encrypt(self, plaintext: bytes, aad: bytes) -> tuple[bytes, bytes, int]: ...
    def decrypt(
        self,
        nonce: bytes,
        ciphertext: bytes,
        aad: bytes,
        seq: int,
        is_prev_epoch: bool,
    ) -> bytes: ...
    def needs_rotation(self) -> bool: ...
    def initiate_rotation(self) -> tuple[int, bytes]: ...
    def complete_rotation_initiator(self, remote_ephemeral_pub: bytes) -> int: ...
    def complete_rotation_responder(
        self, remote_ephemeral_pub: bytes, new_epoch: int
    ) -> tuple[bytes, int]: ...
    def tick(self) -> None: ...
    @property
    def epoch(self) -> int: ...
    @property
    def packets_sent(self) -> int: ...
    @property
    def has_grace_period(self) -> bool: ...

class AesKey:
    def encrypt(self, nonce: bytes, plaintext: bytes, aad: bytes) -> bytes: ...
    def decrypt(self, nonce: bytes, ciphertext: bytes, aad: bytes) -> bytes: ...

def disable_core_dumps() -> None: ...
def harden_process() -> None: ...
