"""Type stubs for the tuncore native Rust extension (PyO3).

PyO3 maps `Vec<u8>` to Python `list[int]` at the FFI boundary; we declare
those returns as `bytes` here so type-checking is useful, but production
callers that hand the value to anything strict (struct.unpack_from,
hmac.compare_digest, os.write) MUST coerce with `bytes(...)`. The cost of
this small lie in the stub is one explicit wrap per call site; the
benefit is that everything downstream type-checks correctly.
"""

class IdentityKeyPair:
    @staticmethod
    def generate() -> IdentityKeyPair: ...
    @property
    def public_key(self) -> bytes: ...
    def encrypt_to_store(self, passphrase: bytes) -> bytes: ...
    @staticmethod
    def decrypt_from_store(blob: bytes, passphrase: bytes) -> IdentityKeyPair: ...
    def compute_hmac(self, context: bytes, data: bytes) -> bytes: ...
    def zeroize(self) -> None: ...

class ReplayWindow:
    def __init__(self) -> None: ...
    def check_and_update(self, seq: int) -> bool: ...
    def check(self, seq: int) -> bool: ...
    def update(self, seq: int) -> None: ...
    @property
    def max_seq(self) -> int: ...

class NonceGenerator:
    def __init__(self, epoch: int) -> None: ...
    def next(self) -> bytes: ...
    @property
    def count(self) -> int: ...
    @property
    def epoch(self) -> int: ...

class NoiseInitiator:
    def __init__(self, identity: IdentityKeyPair) -> None: ...
    def write_message_1(self) -> bytes: ...
    def read_message_2(self, msg: bytes) -> tuple[bytes, bytes]:
        """Returns ``(remote_static_pub, attest_payload)``.

        ``attest_payload`` is exactly ``HANDSHAKE_ATTEST_PAYLOAD_SIZE``
        bytes; the caller parses cert + binding signature framing.
        """
        ...
    def write_message_3(self, attest_payload: bytes) -> bytes:
        """``attest_payload`` must be exactly ``HANDSHAKE_ATTEST_PAYLOAD_SIZE`` bytes."""
        ...
    def into_transport(self) -> NoiseTransport: ...
    def get_handshake_hash(self) -> bytes: ...

class NoiseResponder:
    def __init__(self, identity: IdentityKeyPair) -> None: ...
    def read_message_1(self, msg: bytes) -> None: ...
    def write_message_2(self, attest_payload: bytes) -> bytes:
        """``attest_payload`` must be exactly ``HANDSHAKE_ATTEST_PAYLOAD_SIZE`` bytes."""
        ...
    def read_message_3(self, msg: bytes) -> tuple[bytes, bytes]:
        """Returns ``(remote_static_pub, attest_payload)``."""
        ...
    def into_transport(self) -> NoiseTransport: ...
    def get_handshake_hash(self) -> bytes: ...

class NoiseTransport:
    def encrypt(self, plaintext: bytes) -> bytes: ...
    def decrypt(self, ciphertext: bytes) -> bytes: ...

class SessionKeyManager:
    @staticmethod
    def from_handshake_hash(
        hash: bytes,
        is_initiator: bool,
        rotation_packets: int | None = None,
        rotation_seconds: int | None = None,
    ) -> SessionKeyManager: ...
    @staticmethod
    def from_bootstrap_shared_secret(
        shared_secret: bytes,
        is_initiator: bool,
        rotation_packets: int | None = None,
        rotation_seconds: int | None = None,
    ) -> SessionKeyManager: ...
    def encrypt(self, plaintext: bytes, aad: bytes) -> tuple[bytes, bytes, int]: ...
    def decrypt(
        self,
        nonce: bytes,
        ciphertext: bytes,
        aad: bytes,
        seq: int,
        is_prev_epoch: bool,
    ) -> bytes: ...
    def needs_rotation(self) -> bool: ...
    def initiate_rotation(self) -> tuple[int, bytes]: ...
    def complete_rotation_initiator(self, remote_ephemeral_pub: bytes) -> int: ...
    def complete_rotation_responder(
        self, remote_ephemeral_pub: bytes, new_epoch: int
    ) -> tuple[bytes, int]: ...
    def prepare_rotation_responder(
        self, remote_ephemeral_pub: bytes, new_epoch: int
    ) -> tuple[bytes, int]: ...
    def apply_rotation_responder(self) -> int: ...
    def tick(self) -> None: ...
    @property
    def epoch(self) -> int: ...
    @property
    def packets_sent(self) -> int: ...
    @property
    def has_grace_period(self) -> bool: ...

class AesKey:
    def encrypt(self, nonce: bytes, plaintext: bytes, aad: bytes) -> bytes: ...
    def decrypt(self, nonce: bytes, ciphertext: bytes, aad: bytes) -> bytes: ...

class AttestKey:
    """Device-attestation key. Backend (soft / TPM / Keystore) is chosen at
    Rust compile time; the FFI surface is identical."""

    @staticmethod
    def generate() -> AttestKey:
        """Generate a fresh attestation keypair using the active backend."""
        ...

    def public_spki_der(self) -> bytes:
        """SubjectPublicKeyInfo DER of the verifying key. Non-secret."""
        ...

    def sign(self, msg: bytes) -> bytes:
        """Sign ``msg``. Returns ASN.1 DER ECDSA signature."""
        ...

def disable_core_dumps() -> None: ...
def harden_process() -> None: ...

# Module-level helpers for the post-handshake bootstrap exchange.
def generate_ephemeral() -> tuple[bytes, bytes]:
    """Return ``(secret, public)`` for an X25519 ephemeral keypair."""
    ...

def bootstrap_session_from_dh(
    our_secret: bytes,
    peer_public: bytes,
    is_initiator: bool,
    rotation_packets: int | None = None,
    rotation_seconds: int | None = None,
) -> SessionKeyManager:
    """Derive session keys from an ephemeral DH exchange.

    ``rotation_packets`` / ``rotation_seconds`` override the default
    rotation thresholds (5000 / 600); jitter is always applied.
    """
    ...

# Fixed size of the attestation payload carried in Noise XX msg2 / msg3.
# Producers must pad cert + binding signature + framing to exactly this many
# bytes; receivers get exactly this many bytes back from
# ``NoiseInitiator.read_message_2`` / ``NoiseResponder.read_message_3``.
HANDSHAKE_ATTEST_PAYLOAD_SIZE: int
